name: lox
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-edge.0176bcc73f80c6b174575ff53f80f33e1bac5421

dependencies:
  path:
  collection:
  equatable:

dev_dependencies:
  lints:
  test:
