name: tryit
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0-edge.0176bcc73f80c6b174575ff53f80f33e1bac5421

dependencies:
  web: ^0.5.1
  http:
  path:
  collection:
  lox:
    path: ../

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
