name: tryit
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0-edge.ea4afe3ac61037fd9f9b5040d61448acbca984f4

dependencies:
  web:
  http:
  path:
  collection:
  lox:
    path: ../

dev_dependencies:
  build_runner:
  build_web_compilers:
  lints:
