name: tryit
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0-edge.0176bcc73f80c6b174575ff53f80f33e1bac5421

dependencies:
  web:
  http:
  path:
  collection:
  lox:
    path: ../

dev_dependencies:
  build_runner:
  build_web_compilers:
  lints:
